---
- name: Install and configure fail2ban 
  hosts: all
  tasks:
  - name: Install on Debian
    apt:
      update_cache: true
      name: fail2ban
      state: latest
    when: ansible_facts['os_family'] == 'Debian'

  - name: Install iptables on Debian
    apt:
      update_cache: true
      name: iptables
      state: latest
    when: ansible_facts['os_family'] == 'Debian'

  - name: Optional - Install EpelRelease on RockyLinux
    yum:  
      name: epel-release
      state: latest
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Install on RockyLinux
    yum:
        name: fail2ban
        state: latest
    when: ansible_facts['os_family'] == 'RedHat'

  - name: Copy fail2ban configuration
    copy:
      src: jail.conf
      dest: /etc/fail2ban/jail.local

  - name: Turn off ipv6
    lineinfile:
      path: /etc/fail2ban/fail2ban.conf
      search_string: "#allowipv6 = auto"
      line: "allowipv6 = off"
  
  - name: Edit debian backend
    lineinfile: 
      path: /etc/fail2ban/jail.d/defaults-debian.conf
      line: "backend = systemd"
      create: yes
    when: ansible_facts['os_family'] == 'Debian'

  - name: Reload ssh
    systemd: 
      name: sshd
      state: reloaded

  - name: Restart the service
    systemd:
      enabled: true
      name: fail2ban
      state: restarted